project:
  type: book
  output-dir: docs

book:
  title: "Cuadernos de Estadística Espacial"
  subtitle: "Martha Patricia Bohorquez Castañeda"
  
  
  
# --- SECCIÓN DE GITHUB CORREGIDA ---
  navbar:
    right:
      - icon: github
        href: https://github.com/mpbohorquezc/SpatFD-Functional-Geostatistics.git
  # ---------------------------------
  
  sidebar:
    collapse-level: 1

  chapters:
    - index.qmd
    - part: "<span style='color: #FF8000 !important;'>Análisis Exploratorio de Datos</span>"
      chapters: 
        - text: "<span style='color: #728387 !important;'>Estadística descriptiva y Exploratoria</span>"
          file: 1.qmd
        - text: "<span style='color: #728387 !important;'>Pruebas de bondad de ajuste</span>"
          file: 2-Pruebas_de_Bondad_de_ajuste.qmd
       
    - part: "<span style='color: #FF8000 !important;'>Geoestadística </span>"
      chapters:
        - text: "<span style='color: #728387 !important;'>Geoestadística con Sgeostat</span>"
          file: 1.qmd
        - text: "<span style='color: #728387 !important;'>Geoestadística Univariada con GeoR </span>"
          file: 2.qmd
        - text: "<span style='color: #728387 !important;'>Kriging</span>"
          file: 3.qmd
        - text: "<span style='color: #728387 !important;'>Proceso espacial gaussiano bivariado</span>"
          file: 8-Introduccion_proceso_espacial_bivariado.qmd 
        - text: "<span style='color: #728387 !important;'>Ozono México</span>"
          file: 13-Gstats_datos_de_méxico.qmd           
          
          
          
    - part: "<span style='color: #FF8000 !important;'>Modelos de Regresión Espacial</span>"
      chapters:
        - text: "<span style='color: #728387 !important;'>Aplicación de los Modelos </span>"
          file: 4.qmd
        - text: "<span style='color: #728387 !important;'>Redes </span>"
          file: 3-redes.qmd
        - text: "<span style='color: #728387 !important;'>Encuesta Bogotá Multipropósito </span>"
          file: 14-Encuesta_Multipropoosito.qmd          
          
    
    - part: "<span style='color: #FF8000 !important;'>Estadística Espacial Funcional</span>"
      chapters: 
        - text: "<span style='color: #728387 !important;'>Estadística Espacial Funcional</span>"
          file: 5.qmd
        - text: "<span style='color: #728387 !important;'>Paquete </span>"
          file: 6.qmd
        - text: "<span style='color: #728387 !important;'>FDA-Regresión funcional</span>"
          file: 5-Análisis_de_datos_funcionales (ADF) - Modelos de regresión.qmd
        - text: "<span style='color: #728387 !important;'>FDA-Regresión escalar</span>"
          file: 6-Análisis_de_datos_funcionales (ADF) - Modelos de regresión (Parte 2).qmd   
        - text: "<span style='color: #728387 !important;'>FDA-Regresión escalar</span>"
          file: 7-Análisis de datos funcionales (ADF) - Análisis gráfico.qmd   
        - text: "<span style='color: #728387 !important;'>FDA – Análisis descriptivo</span>"
          file: 9-Análisis_de_datos_funcionales_(ADF) - Análisis exploratorio.qmd        
            
          
    
          
    - part: "<span style='color: #FF8000 !important;'>Objetos </span>"
      chapters:
        - text: "<span style='color: #728387 !important;'>SpatFD</span>"
          file: 7.qmd
        - text: "<span style='color: #728387 !important;'>gfdata </span>"
          file: 8.qmd 
   
    - part: "<span style='color: #FF8000 !important;'>Datasets </span>"
      chapters:
        - text: "<span style='color: #728387 !important;'>AirQualityBogota</span>"
          file: 9.qmd
        - text: "<span style='color: #728387 !important;'>Vowels</span>"
          file: 10.qmd
        - text: "<span style='color: #728387 !important;'>CokMexico</span>"
          file: 11.qmd
          
          
          
          
    - part: "<span style='color: #FF8000 !important;'>Kriging</span>"
      chapters:
        - text: "Teoría de Kriging"
          file: 12.qmd
        - text: "Ilustración del Kriging Simple"
          file: 10-Ilustración_del_kriging_simple_espacio_tiempo.qmd      
      
      
    - part: "<span style='color: #FF8000 !important;'>Cokriging</span>"
      chapters:
        - text: "Modelo de Cokriging"
          file: 13.qmd
        - text: "Ilustración del Cokriging"
          file: 11-Cokriging.qmd
      
    - part: "<span style='color: #FF8000 !important;'>Diseño Óptimo</span>"
      chapters:
        - text: "Diseño Óptimo"
          file: 14.qmd
        - text: "Pulimiento de Medianas"
          file: 12-Pulimiento_de_medianas.qmd
    
  
bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    number-sections: true
    css: custom.css

editor: visual